application: woodpage2017
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/html/\1
  upload: static/(.*\.html)
  expiration: "1h"
# audio files
- url: /(.*\.(mid|midi|mp3|wav))
  static_files: static/\1
  upload: static/(.*\.(mid|midi|mp3|wav))  
# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png|svg))
  static_files: static/img/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: static/\1
  upload: static/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/js/\1
  upload: static/(.*\.js)

- url: /(.*\.ttf)
  mime_type: font/ttf
  static_files: static/fonts/\1
  upload: static/(.*\.ttf)

- url: /(.*\.woff)
  mime_type: font/ttf
  static_files: static/fonts/\1
  upload: static/(.*\.woff)

- url: /(.*\.woff2)
  mime_type: font/ttf
  static_files: static/fonts/\1
  upload: static/(.*\.woff2)

- url: .*
  script: main.app

libraries:
- name: PIL
  version: latest
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"


